const WORKBOOKS = {
  CLASS_INFO: '1YH9Zc3icnhKW5Iw4_q3jBXoNUJXOzNG8S1cO4I92_Yk',
  TERM_TIMETABLE: '1wLLVfZKq5NpTwsE8uRMVZ5nDeqSvk17_N-9eia0zuVE',
  PROF_INFO: '1esbqZ_JZDzCe7i2nNtdAcIoYFDBOx_j3dZ6WFVLMCAA',
};

module.exports = WORKBOOKS;